# This file was automatically generated by SWIG (http://www.swig.org).
# Version 3.0.12
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
if _swig_python_version_info >= (2, 7, 0):
    def swig_import_helper():
        import importlib
        pkg = __name__.rpartition('.')[0]
        mname = '.'.join((pkg, '_fem_lib')).lstrip('.')
        try:
            return importlib.import_module(mname)
        except ImportError:
            return importlib.import_module('_fem_lib')
    _fem_lib = swig_import_helper()
    del swig_import_helper
elif _swig_python_version_info >= (2, 6, 0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_fem_lib', [dirname(__file__)])
        except ImportError:
            import _fem_lib
            return _fem_lib
        try:
            _mod = imp.load_module('_fem_lib', fp, pathname, description)
        finally:
            if fp is not None:
                fp.close()
        return _mod
    _fem_lib = swig_import_helper()
    del swig_import_helper
else:
    import _fem_lib
del _swig_python_version_info

try:
    _swig_property = property
except NameError:
    pass  # Python < 2.2 doesn't have 'property'.

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_setattr_nondynamic(self, class_type, name, value, static=1):
    if (name == "thisown"):
        return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name, None)
    if method:
        return method(self, value)
    if (not static):
        if _newclass:
            object.__setattr__(self, name, value)
        else:
            self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)


def _swig_setattr(self, class_type, name, value):
    return _swig_setattr_nondynamic(self, class_type, name, value, 0)


def _swig_getattr(self, class_type, name):
    if (name == "thisown"):
        return self.this.own()
    method = class_type.__swig_getmethods__.get(name, None)
    if method:
        return method(self)
    raise AttributeError("'%s' object has no attribute '%s'" % (class_type.__name__, name))


def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except __builtin__.Exception:
    class _object:
        pass
    _newclass = 0

class SwigPyIterator(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, SwigPyIterator, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, SwigPyIterator, name)

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _fem_lib.delete_SwigPyIterator
    __del__ = lambda self: None

    def value(self):
        return _fem_lib.SwigPyIterator_value(self)

    def incr(self, n=1):
        return _fem_lib.SwigPyIterator_incr(self, n)

    def decr(self, n=1):
        return _fem_lib.SwigPyIterator_decr(self, n)

    def distance(self, x):
        return _fem_lib.SwigPyIterator_distance(self, x)

    def equal(self, x):
        return _fem_lib.SwigPyIterator_equal(self, x)

    def copy(self):
        return _fem_lib.SwigPyIterator_copy(self)

    def next(self):
        return _fem_lib.SwigPyIterator_next(self)

    def __next__(self):
        return _fem_lib.SwigPyIterator___next__(self)

    def previous(self):
        return _fem_lib.SwigPyIterator_previous(self)

    def advance(self, n):
        return _fem_lib.SwigPyIterator_advance(self, n)

    def __eq__(self, x):
        return _fem_lib.SwigPyIterator___eq__(self, x)

    def __ne__(self, x):
        return _fem_lib.SwigPyIterator___ne__(self, x)

    def __iadd__(self, n):
        return _fem_lib.SwigPyIterator___iadd__(self, n)

    def __isub__(self, n):
        return _fem_lib.SwigPyIterator___isub__(self, n)

    def __add__(self, n):
        return _fem_lib.SwigPyIterator___add__(self, n)

    def __sub__(self, *args):
        return _fem_lib.SwigPyIterator___sub__(self, *args)
    def __iter__(self):
        return self
SwigPyIterator_swigregister = _fem_lib.SwigPyIterator_swigregister
SwigPyIterator_swigregister(SwigPyIterator)

class Scene3d(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, Scene3d, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, Scene3d, name)
    __repr__ = _swig_repr

    def __init__(self):
        this = _fem_lib.new_Scene3d()
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this

    def InitializeGridsAndVelocity(self, grid, idx):
        return _fem_lib.Scene3d_InitializeGridsAndVelocity(self, grid, idx)

    def InitializeConstitutiveModel(self, mu, arg3, method_type):
        return _fem_lib.Scene3d_InitializeConstitutiveModel(self, mu, arg3, method_type)

    def PreComputation(self):
        return _fem_lib.Scene3d_PreComputation(self)

    def ComputeNodalForce(self, external_force):
        return _fem_lib.Scene3d_ComputeNodalForce(self, external_force)

    def ForwardEuler(self, cell_mass, time_step):
        return _fem_lib.Scene3d_ForwardEuler(self, cell_mass, time_step)
    __swig_setmethods__["displacement"] = _fem_lib.Scene3d_displacement_set
    __swig_getmethods__["displacement"] = _fem_lib.Scene3d_displacement_get
    if _newclass:
        displacement = _swig_property(_fem_lib.Scene3d_displacement_get, _fem_lib.Scene3d_displacement_set)
    __swig_setmethods__["velocity"] = _fem_lib.Scene3d_velocity_set
    __swig_getmethods__["velocity"] = _fem_lib.Scene3d_velocity_get
    if _newclass:
        velocity = _swig_property(_fem_lib.Scene3d_velocity_get, _fem_lib.Scene3d_velocity_set)
    __swig_setmethods__["force"] = _fem_lib.Scene3d_force_set
    __swig_getmethods__["force"] = _fem_lib.Scene3d_force_get
    if _newclass:
        force = _swig_property(_fem_lib.Scene3d_force_get, _fem_lib.Scene3d_force_set)
    __swig_destroy__ = _fem_lib.delete_Scene3d
    __del__ = lambda self: None
Scene3d_swigregister = _fem_lib.Scene3d_swigregister
Scene3d_swigregister(Scene3d)

# This file is compatible with both classic and new-style classes.


